package models.enums;

public enum Category {
    CARS, BUSSES, TRUCKS, MOTORBIKES, AGRICULTURE, INDUSTRIAL, WAREHOUSE, CARAVANS, BOATS, TRAILERS, BIKES, PARTS,
    ACCESSORIES, TIRES, BUYS, SERVICES
}
